logging:
  level:
    org.springframework: INFO
    com.Project: DEBUG
    reactor.netty: DEBUG
    reactor.core: DEBUG
    org.springframework.web.reactive: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mscontol
    username: postgres
    password: omar
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.profiles.active}-${server.port}
  client:
    service-url:
      default-zone: http://localhost:8761
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      userServiceBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5              # Regarde les 5 derniers appels
        failureRateThreshold: 50          # 50% d'échecs => OPEN
        waitDurationInOpenState: 5s       # Reste OPEN 5 secondes
        permittedNumberOfCallsInHalfOpenState: 2  # 2 appels de test
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5

  retry:
    instances:
      myRetry:
        max-attempts: 3                   # 3 tentatives max
        wait-duration: 500ms              # Attente entre les tentatives
        retry-exceptions:
          - java.lang.RuntimeException

  timelimiter:
    instances:
      myTimeout:
        timeout-duration: 1s              # Timeout après 1 seconde
