server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_dev
    username: root
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: update

app:
  name: User Management Service
  version: 1.0.0
