app:
  name: User Management Service
  version: 1.0.0

logging:
  level:
    org.springframework: INFO
    ma.gov.pfe: DEBUG
    reactor.netty: DEBUG
    reactor.core: DEBUG
    org.springframework.web.reactive: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mscontol
    username: postgres
    password: omar
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
